name: Build All

on:
  push:
    branches:
      - master

env:
  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pproduction=true build

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pproduction=true publish
