name: Build All

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          ls /Library/Developer/CommandLineTools/usr/lib/clang/
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Set up caching
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pproduction=true build

      - name: Gradle Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pproduction=true publish
